# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(540, 394)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(20, 60, 91, 23))
        self.startButton.setObjectName("startButton")
        self.symLine = QtWidgets.QLineEdit(self.centralwidget)
        self.symLine.setGeometry(QtCore.QRect(20, 30, 91, 20))
        self.symLine.setObjectName("symLine")
        self.symLabel = QtWidgets.QLabel(self.centralwidget)
        self.symLabel.setGeometry(QtCore.QRect(20, 10, 41, 20))
        self.symLabel.setObjectName("symLabel")
        self.logPlain = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.logPlain.setGeometry(QtCore.QRect(130, 30, 391, 81))
        self.logPlain.setObjectName("logPlain")
        self.logLabel = QtWidgets.QLabel(self.centralwidget)
        self.logLabel.setGeometry(QtCore.QRect(130, 10, 47, 21))
        self.logLabel.setObjectName("logLabel")
        self.plotGraphics = QtWidgets.QGraphicsView(self.centralwidget)
        self.plotGraphics.setGeometry(QtCore.QRect(20, 140, 501, 192))
        self.plotGraphics.setObjectName("plotGraphics")
        self.plotLabel = QtWidgets.QLabel(self.centralwidget)
        self.plotLabel.setGeometry(QtCore.QRect(20, 120, 101, 21))
        self.plotLabel.setObjectName("plotLabel")
        self.companyLabel = QtWidgets.QLabel(self.centralwidget)
        self.companyLabel.setGeometry(QtCore.QRect(20, 340, 501, 31))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(112, 112, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(112, 112, 112))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.companyLabel.setPalette(palette)
        self.companyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.companyLabel.setObjectName("companyLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 540, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Fundamentals Python Bot"))
        self.startButton.setText(_translate("MainWindow", "Start Analysis"))
        self.symLabel.setText(_translate("MainWindow", "Symbol"))
        self.logLabel.setText(_translate("MainWindow", "Logging"))
        self.plotLabel.setText(_translate("MainWindow", "Market Distribution"))
        self.companyLabel.setText(_translate("MainWindow", "M&N Investing\n"
"www.mql5.com/en/users/murilofregonesi"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
